#!/usr/bin/env bash

set -e

DOCKER_NAME=clusterit-ssh-test-server

cd "$(dirname "$0")/../test"

docker build -t $DOCKER_NAME .

docker stop $DOCKER_NAME || true

docker run -dit --rm --hostname raspberrypi --name $DOCKER_NAME -p 8000:22 $DOCKER_NAME

cd ..

cargo run -- --config ./test/config.toml --log-level debug

docker stop $DOCKER_NAME 